version: '3.4'

services:
  item-reseller:
    environment:
      - ssl_insecure=1
      - EMAIL_USER=chblaze@gmail.com
      - EMAIL_PASSWORD=ChangeMe

    build: .
    ports:
      - "8801:8801"
    volumes:
      - .:/usr/src/app
